/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest
         * @description Ingest a document through the full spine and index its fossils.
         */
        post: operations["ingest_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/excavate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Excavate
         * @description Embed the query and return the top-k nearest fossil chunks + metadata.
         */
        get: operations["excavate_excavate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mutate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mutate
         * @description Retrieve relevant fossils and return an LLM summary/edit grounded in them.
         *
         *     Prompt Fossilization: the (model, query, instruction, retrieved-fossils)
         *     tuple keys a cache; a repeat request is served from the cache instantly
         *     (``cached=True``) with no LLM call. The default ``mock`` provider keeps this
         *     callable at $0; set ``llm_provider=bedrock`` for a real Claude summary.
         */
        post: operations["mutate_mutate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timetravel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Timetravel
         * @description Return a document's fossils at a chosen layer (Time-Travel Query).
         */
        get: operations["timetravel_timetravel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Diff
         * @description Show changes between two fossil layers of a document (Fossil Diff).
         */
        get: operations["diff_diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enrich": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enrich
         * @description Extract structured markers (dates/metrics/error codes) and persist them.
         *
         *     Automated Enrichment (use case #3): the markers become a fossil-layer-
         *     versioned structured record, retrievable via ``/markers``.
         */
        post: operations["enrich_enrich_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Markers
         * @description Return the stored enrichment record for a document layer.
         */
        get: operations["markers_markers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Chat-Based Fossil Excavation: answer the latest turn, grounded in fossils.
         *
         *     Retrieves for the latest user message (optionally scoped to one document),
         *     answers via the LLM with the full conversation, and cites the fossils used
         *     (with geological age). Prompt Fossilization caches per (model, dialogue,
         *     retrieved fossils).
         */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slide/mutate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Slide Mutate
         * @description PowerPoint Slide Mutator: propose an edit + show the diff, with versioning.
         *
         *     Composes the LLM (edit), Fossil Diff (original vs suggestion), and — when
         *     ``persist`` + ``source_id`` are given — version tracking by saving the
         *     suggestion as a new fossil layer (then visible via ``/timetravel`` & ``/diff``).
         */
        post: operations["slide_mutate_slide_mutate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dataset
         * @description Fine-Tuning Dataset Builder: JSONL instruction/response pairs from fossils.
         */
        post: operations["dataset_dataset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChatMessage
         * @description One turn of a Chat-Based Fossil Excavation conversation.
         *
         *     ``role`` is constrained to user/assistant so an invalid role is rejected at
         *     the API validation layer (422) rather than forwarded to the LLM provider
         *     (which would surface as an opaque 502).
         */
        ChatMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
            /**
             * K
             * @default 5
             */
            k: number;
            /** Source Id */
            source_id?: string | null;
        };
        /**
         * ChatResponse
         * @description Assistant answer grounded in retrieved fossils, with citations.
         */
        ChatResponse: {
            /** Answer */
            answer: string;
            /** Model Id */
            model_id: string;
            /** Mock */
            mock: boolean;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /** Citations */
            citations: components["schemas"]["ExcavateHit"][];
            /** Latency Ms */
            latency_ms: number;
        };
        /** DatasetRequest */
        DatasetRequest: {
            /** Source Id */
            source_id: string;
            /** Version */
            version?: number | null;
            /**
             * Fmt
             * @default chat
             */
            fmt: string;
            /** Templates */
            templates?: string[] | null;
        };
        /**
         * DatasetResponse
         * @description A fine-tuning dataset built from a fossil layer (records + JSONL).
         */
        DatasetResponse: {
            /** Source Id */
            source_id: string;
            /** Version */
            version: number;
            /** Format */
            format: string;
            /** Count */
            count: number;
            /** Records */
            records: {
                [key: string]: unknown;
            }[];
            /** Jsonl */
            jsonl: string;
        };
        /**
         * EnrichmentRecord
         * @description A document layer's extracted markers — the structured enrichment record.
         */
        EnrichmentRecord: {
            /** Source Id */
            source_id: string;
            /** Doc Id */
            doc_id: string;
            /** Layer Version */
            layer_version: number;
            /** Markers */
            markers: components["schemas"]["Marker"][];
            /** Counts */
            counts: {
                [key: string]: number;
            };
        };
        /**
         * ExcavateHit
         * @description A retrieved chunk plus its similarity score (served layer).
         */
        ExcavateHit: {
            /** Chunk Id */
            chunk_id: string;
            /** Doc Id */
            doc_id: string;
            /**
             * Source Id
             * @default
             */
            source_id: string;
            /** Ordinal */
            ordinal: number;
            /** Content */
            content: string;
            /**
             * Score
             * @description Cosine similarity in [-1, 1]; higher is closer.
             */
            score: number;
            /** Layer Version */
            layer_version: number;
            /** Geological Age */
            geological_age: string;
            /** Metadata */
            metadata?: {
                [key: string]: string;
            };
        };
        /** ExcavateResponse */
        ExcavateResponse: {
            /** Query */
            query: string;
            /** K */
            k: number;
            /** Hits */
            hits: components["schemas"]["ExcavateHit"][];
            /** Latency Ms */
            latency_ms: number;
        };
        /**
         * FossilDiffResponse
         * @description Changes between two fossil layers of the same document.
         */
        FossilDiffResponse: {
            /** Source Id */
            source_id: string;
            /** From Version */
            from_version: number;
            /** To Version */
            to_version: number;
            /** Changed */
            changed: boolean;
            /** Added Lines */
            added_lines: number;
            /** Removed Lines */
            removed_lines: number;
            /** Unified Diff */
            unified_diff: string;
        };
        /**
         * FossilLayerChunk
         * @description One chunk of a specific fossil layer (served without its embedding).
         */
        FossilLayerChunk: {
            /** Chunk Id */
            chunk_id: string;
            /** Doc Id */
            doc_id: string;
            /** Source Id */
            source_id: string;
            /** Ordinal */
            ordinal: number;
            /** Content */
            content: string;
            /** Layer Version */
            layer_version: number;
            /** Geological Age */
            geological_age: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestRequest */
        IngestRequest: {
            /** Filename */
            filename: string;
            /** Text */
            text: string;
            /**
             * Content Type
             * @default text/plain
             */
            content_type: string;
            /** User Id */
            user_id?: string | null;
            /** Source Id */
            source_id?: string | null;
            /**
             * Layer Version
             * @default 1
             */
            layer_version: number;
        };
        /**
         * IngestResult
         * @description Summary returned by the ingestion pipeline / ``POST /ingest``.
         */
        IngestResult: {
            /** Doc Id */
            doc_id: string;
            /** Filename */
            filename: string;
            /** Chunks Total */
            chunks_total: number;
            /** Chunks Indexed */
            chunks_indexed: number;
            /** Layer Version */
            layer_version: number;
            /** Embed Model */
            embed_model: string;
            /** Embed Dim */
            embed_dim: number;
        };
        /**
         * Marker
         * @description A structured marker extracted from a document (Automated Enrichment).
         */
        Marker: {
            /** Kind */
            kind: string;
            /** Text */
            text: string;
            /** Value */
            value?: string | null;
        };
        /** MutateRequest */
        MutateRequest: {
            /** Query */
            query: string;
            /**
             * K
             * @default 5
             */
            k: number;
            /** Instruction */
            instruction?: string | null;
        };
        /**
         * MutateResponse
         * @description Result of ``/mutate``: a summary/edit grounded in retrieved fossils.
         *
         *     ``mock`` is True while the LLM is the PR0 placeholder; PR4 swaps in AWS
         *     Bedrock (Converse API) + Prompt Fossilization behind a provider interface
         *     and flips it to False.
         */
        MutateResponse: {
            /** Query */
            query: string;
            /** Instruction */
            instruction?: string | null;
            /** Summary */
            summary: string;
            /** Model Id */
            model_id: string;
            /** Mock */
            mock: boolean;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /** Used Chunks */
            used_chunks: components["schemas"]["ExcavateHit"][];
            /**
             * Note
             * @default
             */
            note: string;
            /** Latency Ms */
            latency_ms: number;
        };
        /** SlideMutateRequest */
        SlideMutateRequest: {
            /**
             * Text
             * @description Slide text to revise.
             */
            text: string;
            /** Instruction */
            instruction: string;
            /** Source Id */
            source_id?: string | null;
            /**
             * Persist
             * @default false
             */
            persist: boolean;
        };
        /**
         * SlideMutateResponse
         * @description PPTX Slide Mutator: an edit suggestion + the diff, with optional versioning.
         */
        SlideMutateResponse: {
            /** Source Id */
            source_id?: string | null;
            /** Instruction */
            instruction: string;
            /** Original */
            original: string;
            /** Suggestion */
            suggestion: string;
            /** Model Id */
            model_id: string;
            /** Mock */
            mock: boolean;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /** Changed */
            changed: boolean;
            /** Added Lines */
            added_lines: number;
            /** Removed Lines */
            removed_lines: number;
            /** Unified Diff */
            unified_diff: string;
            /** Persisted Version */
            persisted_version?: number | null;
        };
        /**
         * TimeTravelResponse
         * @description A document's fossils at a chosen layer + how it relates to the latest.
         */
        TimeTravelResponse: {
            /** Source Id */
            source_id: string;
            /** Version */
            version: number;
            /** Latest Version */
            latest_version: number;
            /** Available Versions */
            available_versions: number[];
            /** Is Latest */
            is_latest: boolean;
            /** Chunks */
            chunks: components["schemas"]["FossilLayerChunk"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ingest_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    excavate_excavate_get: {
        parameters: {
            query: {
                /** @description Natural-language query. */
                q: string;
                /** @description Number of fossils to return. */
                k?: number;
                /** @description Scope to one document (optional). */
                source_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExcavateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mutate_mutate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MutateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timetravel_timetravel_get: {
        parameters: {
            query: {
                /** @description Stable logical-document id. */
                source_id: string;
                /** @description Fossil layer; default = latest. */
                version?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeTravelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diff_diff_get: {
        parameters: {
            query: {
                source_id: string;
                from_version: number;
                to_version: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FossilDiffResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enrich_enrich_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichmentRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    markers_markers_get: {
        parameters: {
            query: {
                source_id: string;
                version?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichmentRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    slide_mutate_slide_mutate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlideMutateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlideMutateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dataset_dataset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatasetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
